### ISSUE TITLE
include standalone python3.exe 

### ISSUE THREAD

**Issue by valq7711** [nicozanf/py4web-pyinstaller#1]
Hello Nico!
Thanks for your work! It is very useful!
Could you also include standalone `python3.exe` (or `py.exe`) similar to web2py binaries?
Thank you in advance!

**Comment by nicozanf** [comment]
Hi,
you're welcome! This is my first GitHub Issue ever ;-)

Well, this is not easy to do because PyInstaller is not meant for it. Anyway, I was already thinking about this need ... maybe we should implement a switch for running py4web in interactive shell...

**Comment by valq7711** [comment]
I found the solution! works fine

```python
# core.py
# add CL args to get_args
   ...
    parser.add_argument(
        "-con",
        "--console_only",
        action="store_true",
        default=False,
        help="Run python console",
    )
    parser.add_argument(
        "--exec",
        type=str,
        default=None,
        help="Run python script",
    )

# add logic in the main 
def main(args=None):
   # allow to run python console and execute python scripts from binaries 
    action.args = args = args or get_args()
    if args.console_only:
        import code
        code.InteractiveConsole(locals = globals()).interact()
        return
    if args.exec:    
        importlib.machinery.SourceFileLoader(
                    '__main__', args.exec
                    ).load_module()    
        return             

     """The main entry point: Start the server and create folders"""
     # Store args in the action to make them visible
    ...
```

**Comment by nicozanf** [comment]
Yes, I was working on a feature like this!.

I prefer:         

import code, site
        code.interact(local=locals())

because  you need the site import, too, for PyInstaller. But this is the right picture.

I'm setting up a PR, but feel fre to do it by yourself ;-)

nico

**Comment by nicozanf** [comment]
Hi, I've just made this PR: https://github.com/web2py/py4web/pull/147 (I prefer to use 'shell' as the name of the option, with all the p4w variables and modules).   

If you think it's useful, make a PR to py4web for the --exec option.

Nico

**Comment by valq7711** [comment]
Thank you!
About --exec:   I need to figure out how to pass down CL args to the target
python script

пн, 6 апр. 2020 г. в 01:05, Nico Zanferrari <notifications@github.com>:
