### ISSUE TITLE
Missing folders/files/setting to be able to support other DB's than sqlite. 

### ISSUE THREAD

**Issue by mrworm** [nicozanf/py4web-pyinstaller#3]
Error: 
RuntimeError: No driver of supported ones ('MySQLdb', 'pymysql', 'mysqlconnector') is available
)
Caused by:
pydal folder is not in the .zip. 
gluon folder is not in the .zip.
And In settings py add the DAL:
from py4web.core import required_folder, DAL

**Comment by nicozanf** [comment]
I'm sorry but this is by design, in order to keep the binary ZIP file simple and light. If you need support for other db drivers it's better to switch to another installation procedure.
